# -*- coding: utf-8 -*-
"""AI and ML contd...

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13wsr0O0bAiHuU1Qeg9tN36KZRdkCMDiM

**class 3 contd...**
"""

#function
def a():
  print('hello')
a()
a()

def add(a,b):
  print(a+b);
a=int(input())
b=int(input())
add(a,b)

"""**class4**"""

#use of iter and next
list=[1,2,3,4,5]
myit=iter(list)

#use of next
print(next(myit))
#stop iteration is coming because we have run all the index values

list=[1,2,3,4,5]
for x in list:
  print(x)

for x in range(1,10,2):
  print(x)

for i in range(10):
  print("The square of ",i," is ",i*i)

a=int(input())
sum=0
for x in range(a):
  sum=sum+x
print('the sum of first ',a-1,' is ',sum)

#factorial using for loop
fact=1
for x in range(1,6):
  fact=fact*x
print('the factorial of 5 is',fact)
#factorial using while loop
fact=1
i=1
while i<=5:
  fact=fact*i
  i=i+1
print("factorial of 5 is ",fact)
#factorial using reverse for loop
fact=1
for i in range(10,0,-1):
  fact=fact*i
print('factorial of 10 is ',fact)
#factorial using reverse while loop
fact=1
i=10
while i>=1:
  fact=fact*i
  i-=1
print('factorial of 10 is ',fact)

import math
print(math.factorial(10))

#to check whether a number is pallindrome or not
a=int(input('Enter a number-'))
rev=0
i=a
while i>0:
  dig=i%10
  i=i//10                       #divide symbol is this "//" not this "/"
  rev=rev*10+dig
if(rev==a):
  print('Number is pallindrome')
else:
  print('Number is not pallindrome')

#module
#printing time in ist
import datetime
x=datetime.datetime.now()+datetime.timedelta(hours=5, minutes=30)
print(x)

#printing calender
import calendar
print(calendar.calendar(2023))

import calendar
print(calendar.month(2023,8))

import random
list=['a','b','c','d','e','f','g']
print(random.randint(0,5))
print(random.choice(list))

#slicing
s="hello jai anand"
print(s[0:5])
print(s[6:9])
print(s[6:])
print(s[:9])
print(s[:])

"""**class5**"""

#reading a file
myfile=open("a.txt","r")
print(myfile.read())
myfile.close()

#writing a file
myfile=open("a.txt","w")
myfile.write("this is written by the user-")
myfile.close()

#writing a file
myfile=open("a.txt","w")
myfile.write(input("this is user inputted-"))
myfile.close()

#appending a file
myfile=open("a.txt","a")
myfile.write(input())
myfile.close()

#context manager
with open ("a.txt","r") as myfile:
  print(myfile.read())

#writelines()
mylines=['good evening\n','welcome to nda\n']
with open("a.txt","w") as file1:
  file1.writelines(mylines)

#calculator
a=int(input())
b=int(input())
sum=a+b
a=str(sum)
mylines=['sum of two numbers',a]
with open('a.txt','a') as file1:
  file1.writelines(mylines)

# % operator
print('%d %s all %s'%(6,'hello','anand'))

# .format()
print('hello {1}thank you {0}'.format('welcome','all\n'))

#fstring 
a=10
b=10
print(f"addition of {a} and {b} is {a+b}")